apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"   # pour que métallb utilise une ip pour tout les services 
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin
  ports:
  - protocol: TCP
    port: 5000        #port d'exposition au loadbalancer
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: my_php_my_admin
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 15 #Kubelet qu'il devrait attendre 5 secondes avant d'effectuer la première probe
          periodSeconds: 5 #Kubelet doit effectuer un check de liveness toutes les 5 secondes
        env:
        - name: PMA_HOST
          value: mysql
        - name: PMA_PORT
          value: '3306'
        - name: PMA_USER
          value: root
        - name: MYSQL_ROOT_PASSWORD
          value: password